--
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: media
  destination:
    namespace: media  #update namespace name if you wish
    name: cluster1   #update cluster name if its different
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.4.0"
    chart: ingress-nginx
    helm:
      values: |
        controller:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: latest
        dnsPolicy: ClusterFirst
        env:
          TZ: Europe/London
          UMASK: "002"
          PUID: "3001"
          PGID: "513"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - golf
        service:
          sonarr:
            ports:
              https:
                port: 8989
        ingress:
          sonarr:
            enabled: true
            ingressClass: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
            hosts:
              - host: "sonarr.theclarkhome.com"
                paths:
                  - path: /
                    backend:
                      name: sonarr
                      service:
                        port: 8989
            tls:
              - hosts:
                - "*.theclarkhome.com"
        persistence:
          config:
            enabled: true
            type: hostPath
            mountPath: /config
            hostPath: /opt/appdata/sonarr
          data:
            enabled: true
            type: nfs
            server: 10.58.0.12
            path: /srv/media


