apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-kitops
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mergwyn/k8s-gitops.git
      revision: HEAD
      directories:
      - path: managementstack/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mergwyn/k8s-gitops.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
          automated:
              allowEmpty: true
              prune: true
              selfHeal: true
