apiVersion: v2
name: kube-prom-stack
description: Helm chart for kube-prom-stack
type: application
version: 0.1.0
appVersion: "1.0"


dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 51.5.3
