apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - install.yaml
  - argocd-ingress.yaml


## changes to config maps
patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yaml

namespace: argocd
