---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  #namespace: argocd
data:
  server.insecure: "true"
  server.log.level: debug
  reposerver.log.level: debug
  applicationsetcontroller.log.level: debug
