apiVersion: v2
name: cloudflare-remote-tunnel
description: Helm chart for cloudflare-remote-tunnel
type: application
version: 0.1.0
appVersion: "1.0"


dependencies:
  - name: cloudflare-remote-tunnel
    repository: https://cloudflare.github.io/helm-charts
    version: 0.1.1
